name: Build container
permissions:
  contents: read
  packages: write
on:
  schedule:
    - cron: "0 0 * * 6"
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
jobs:
  build:
    name: Build container
    runs-on: ubuntu-latest 
    
    env:
      IMAGE_NAME: ${{ github.event.repository.name }}
      REGISTRY: ghcr.io/${{ github.repository_owner }}
      REPO_URL: https://github.com/defrostediceman/ephemeral-hosted-actions-runner
      TOKEN: YOU_SHOULD_USE_A_SECRET_HERE
   
    steps:
      - name: Clone the repository
        uses: actions/checkout@v4

      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman
          podman --version

      - name: Build image
        run: |
          sudo podman build \
            --build-arg REPO_URL=${{ env.REPO_URL }} \
            --build-arg TOKEN=${{ env.TOKEN }} \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
            -f ./Containerfile .

      - name: Login to GHCR
        run: |
          sudo mkdir -p /root/.docker
          sudo touch /root/.docker/config.json
          echo '{"auths":{}}' | sudo tee -a /root/.docker/config.json
          echo ${{ secrets.GITHUB_TOKEN }} | sudo podman login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          sudo podman push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          sudo podman push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Cleanup
        if: always()
        run: |
          sudo podman logout ${{ env.REGISTRY }}
          sudo podman system prune -af
          sudo rm -rf /root/.docker